// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: evse-api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Evse_AddEVSE_FullMethodName       = "/api.Evse/AddEVSE"
	Evse_GetEVSEs_FullMethodName      = "/api.Evse/GetEVSEs"
	Evse_GetEVSE_FullMethodName       = "/api.Evse/GetEVSE"
	Evse_SetEVCC_FullMethodName       = "/api.Evse/SetEVCC"
	Evse_SetPowerMeter_FullMethodName = "/api.Evse/SetPowerMeter"
	Evse_GetEVSEUsage_FullMethodName  = "/api.Evse/GetEVSEUsage"
)

// EvseClient is the client API for Evse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Evse settings
type EvseClient interface {
	AddEVSE(ctx context.Context, in *AddEvseRequest, opts ...grpc.CallOption) (*AddEvseResponse, error)
	GetEVSEs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetEvsesResponse, error)
	GetEVSE(ctx context.Context, in *GetEvseRequest, opts ...grpc.CallOption) (*GetEvseResponse, error)
	SetEVCC(ctx context.Context, in *SetEVCCRequest, opts ...grpc.CallOption) (*SetEvccResponse, error)
	SetPowerMeter(ctx context.Context, in *SetPowerMeterRequest, opts ...grpc.CallOption) (*SetPowerMeterResponse, error)
	GetEVSEUsage(ctx context.Context, in *GetUsageForEVSERequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUsageForEVSEResponse], error)
}

type evseClient struct {
	cc grpc.ClientConnInterface
}

func NewEvseClient(cc grpc.ClientConnInterface) EvseClient {
	return &evseClient{cc}
}

func (c *evseClient) AddEVSE(ctx context.Context, in *AddEvseRequest, opts ...grpc.CallOption) (*AddEvseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEvseResponse)
	err := c.cc.Invoke(ctx, Evse_AddEVSE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evseClient) GetEVSEs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetEvsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvsesResponse)
	err := c.cc.Invoke(ctx, Evse_GetEVSEs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evseClient) GetEVSE(ctx context.Context, in *GetEvseRequest, opts ...grpc.CallOption) (*GetEvseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvseResponse)
	err := c.cc.Invoke(ctx, Evse_GetEVSE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evseClient) SetEVCC(ctx context.Context, in *SetEVCCRequest, opts ...grpc.CallOption) (*SetEvccResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetEvccResponse)
	err := c.cc.Invoke(ctx, Evse_SetEVCC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evseClient) SetPowerMeter(ctx context.Context, in *SetPowerMeterRequest, opts ...grpc.CallOption) (*SetPowerMeterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPowerMeterResponse)
	err := c.cc.Invoke(ctx, Evse_SetPowerMeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evseClient) GetEVSEUsage(ctx context.Context, in *GetUsageForEVSERequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUsageForEVSEResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Evse_ServiceDesc.Streams[0], Evse_GetEVSEUsage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUsageForEVSERequest, GetUsageForEVSEResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Evse_GetEVSEUsageClient = grpc.ServerStreamingClient[GetUsageForEVSEResponse]

// EvseServer is the server API for Evse service.
// All implementations must embed UnimplementedEvseServer
// for forward compatibility.
//
// Evse settings
type EvseServer interface {
	AddEVSE(context.Context, *AddEvseRequest) (*AddEvseResponse, error)
	GetEVSEs(context.Context, *emptypb.Empty) (*GetEvsesResponse, error)
	GetEVSE(context.Context, *GetEvseRequest) (*GetEvseResponse, error)
	SetEVCC(context.Context, *SetEVCCRequest) (*SetEvccResponse, error)
	SetPowerMeter(context.Context, *SetPowerMeterRequest) (*SetPowerMeterResponse, error)
	GetEVSEUsage(*GetUsageForEVSERequest, grpc.ServerStreamingServer[GetUsageForEVSEResponse]) error
	mustEmbedUnimplementedEvseServer()
}

// UnimplementedEvseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEvseServer struct{}

func (UnimplementedEvseServer) AddEVSE(context.Context, *AddEvseRequest) (*AddEvseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEVSE not implemented")
}
func (UnimplementedEvseServer) GetEVSEs(context.Context, *emptypb.Empty) (*GetEvsesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEVSEs not implemented")
}
func (UnimplementedEvseServer) GetEVSE(context.Context, *GetEvseRequest) (*GetEvseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEVSE not implemented")
}
func (UnimplementedEvseServer) SetEVCC(context.Context, *SetEVCCRequest) (*SetEvccResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEVCC not implemented")
}
func (UnimplementedEvseServer) SetPowerMeter(context.Context, *SetPowerMeterRequest) (*SetPowerMeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPowerMeter not implemented")
}
func (UnimplementedEvseServer) GetEVSEUsage(*GetUsageForEVSERequest, grpc.ServerStreamingServer[GetUsageForEVSEResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetEVSEUsage not implemented")
}
func (UnimplementedEvseServer) mustEmbedUnimplementedEvseServer() {}
func (UnimplementedEvseServer) testEmbeddedByValue()              {}

// UnsafeEvseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvseServer will
// result in compilation errors.
type UnsafeEvseServer interface {
	mustEmbedUnimplementedEvseServer()
}

func RegisterEvseServer(s grpc.ServiceRegistrar, srv EvseServer) {
	// If the following call pancis, it indicates UnimplementedEvseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Evse_ServiceDesc, srv)
}

func _Evse_AddEVSE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEvseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvseServer).AddEVSE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Evse_AddEVSE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvseServer).AddEVSE(ctx, req.(*AddEvseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evse_GetEVSEs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvseServer).GetEVSEs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Evse_GetEVSEs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvseServer).GetEVSEs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evse_GetEVSE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvseServer).GetEVSE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Evse_GetEVSE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvseServer).GetEVSE(ctx, req.(*GetEvseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evse_SetEVCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEVCCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvseServer).SetEVCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Evse_SetEVCC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvseServer).SetEVCC(ctx, req.(*SetEVCCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evse_SetPowerMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvseServer).SetPowerMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Evse_SetPowerMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvseServer).SetPowerMeter(ctx, req.(*SetPowerMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evse_GetEVSEUsage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUsageForEVSERequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EvseServer).GetEVSEUsage(m, &grpc.GenericServerStream[GetUsageForEVSERequest, GetUsageForEVSEResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Evse_GetEVSEUsageServer = grpc.ServerStreamingServer[GetUsageForEVSEResponse]

// Evse_ServiceDesc is the grpc.ServiceDesc for Evse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Evse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Evse",
	HandlerType: (*EvseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEVSE",
			Handler:    _Evse_AddEVSE_Handler,
		},
		{
			MethodName: "GetEVSEs",
			Handler:    _Evse_GetEVSEs_Handler,
		},
		{
			MethodName: "GetEVSE",
			Handler:    _Evse_GetEVSE_Handler,
		},
		{
			MethodName: "SetEVCC",
			Handler:    _Evse_SetEVCC_Handler,
		},
		{
			MethodName: "SetPowerMeter",
			Handler:    _Evse_SetPowerMeter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEVSEUsage",
			Handler:       _Evse_GetEVSEUsage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "evse-api.proto",
}
