syntax = "proto3";

package api;
option go_package = "github.com/ChargePi/ChargePi-go/pkg/proto/v1/grpc";

import "hardware.proto";
import "enums.proto";
import "google/protobuf/empty.proto";

service ChargePoint {
  // Display settings
  rpc SetDisplaySettings (SetDisplaySettingsRequest) returns (SetDisplaySettingsResponse) {}
  rpc GetDisplaySettings (google.protobuf.Empty) returns (GetDisplaySettingsResponse) {}

  // Reader settings
  rpc SetReaderSettings (SetReaderSettingsRequest) returns (SetReaderSettingsResponse) {}
  rpc GetReaderSettings (google.protobuf.Empty) returns (GetReaderSettingsResponse) {}

  // LED indicator
  rpc SetIndicatorSettings (SetIndicatorSettingsRequest) returns (SetIndicatorSettingsResponse) {}
  rpc GetIndicatorSettings (google.protobuf.Empty) returns (GetIndicatorSettingsResponse) {}

  // Connection settings
  rpc GetConnectionDetails(google.protobuf.Empty) returns (GetConnectionDetailsResponse) {}
  rpc ChangeConnectionDetails(ChangeConnectionDetailsRequest) returns (ChangeConnectionDetailsResponse) {}

  // Charge point details
  rpc GetChargePointDetails(google.protobuf.Empty) returns (GetChargePointDetailsResponse) {}
  rpc ChangeChargePointDetails(ChangeChargePointDetailsRequest) returns (ChangeChargePointDetailsResponse) {}

  // Details
  rpc GetVersion(google.protobuf.Empty) returns (GetVersionResponse) {}
  rpc GetStatus(google.protobuf.Empty) returns (GetStatusResponse) {}

  rpc Restart(RestartRequest) returns (google.protobuf.Empty) {}

  // Disconnect
  rpc Disconnect(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  // Connect
  rpc Connect(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  //rpc StartCharging(StartChargingRequest) returns (StartChargingResponse) {}
  //rpc StopCharging(StopChargingRequest) returns (StopChargingResponse) {}
}

/*------------------ ConnectionDetails ------------------------ */

message GetConnectionDetailsResponse {
  ConnectionSettings ConnectionSettings = 1;
}

message ChangeConnectionDetailsRequest {
  ConnectionSettings ConnectionSettings = 1;
}

message ChangeConnectionDetailsResponse {
  ConnectionSettings ConnectionSettings = 1;
  string status = 2;
}

/*------------------ ChargePointDetails ------------------------ */

message ChangeChargePointDetailsRequest {
  ChargePointInfo ChargePointInfo = 1;
}

message ChangeChargePointDetailsResponse {
  string status = 2;
}

message GetChargePointDetailsResponse {
  ChargePointInfo ChargePointInfo = 1;
}

/*------------------ ChargePointDetails ------------------------ */

message GetVersionResponse {
  string Version = 1;
}

message GetStatusResponse {
  bool Connected = 1;
  string Status = 2;
}

/*------------------ Restart ------------------------ */

message RestartRequest {
  string type = 1;
}

/*------------------ Display ------------------------ */

message SetDisplaySettingsRequest {
  Display Display = 1;
}

message SetDisplaySettingsResponse {
  string status = 1;
}

message GetDisplaySettingsResponse {
  Display Display = 1;
}

/*------------------ Reader ------------------------ */

message SetReaderSettingsRequest {
  TagReader Reader = 1;
}

message SetReaderSettingsResponse {
  string status = 1;
}

message GetReaderSettingsResponse {
  TagReader Reader = 1;
}

/*------------------ Indication ------------------------ */

message SetIndicatorSettingsRequest {
  Indicator Indicator = 1;
}

message SetIndicatorSettingsResponse {
  string status = 1;
}

message GetIndicatorSettingsResponse {
  Indicator Indicator = 1;
}

message ConnectionSettings{
  optional string chargePointId = 1;
  optional string url = 2;
  ProtocolVersion ProtocolVersion = 3;
  optional string BasicAuthUsername = 4;
  optional string BasicAuthPassword = 5;
  optional TLS TLS = 6;
}

message TLS {
  optional string CACertificate = 1;
  optional string ClientCertificate = 2;
  optional string ClientPrivateKey = 3;
}

message ChargePointInfo{
  optional string Type = 1;
  optional float MaxPower = 2;
  OcppInfo OcppInfo = 4;
  FreeCharging FreeCharging = 5;
}

message OcppInfo{
  string Vendor = 1;
  string Model = 2;
  optional string Iccid = 3;
  optional string Imsi = 4;
  optional string ChargeBoxSerialNumber = 5;
  optional string ChargePointSerialNumber = 6;
}

message FreeCharging{
  bool Enabled = 1;
  optional int32 MaxChargingTime = 2;
}