syntax = "proto3";

package api;
option go_package = "github.com/ChargePi/ChargePi-go/pkg/proto/v1/grpc";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "enums.proto";

// Local auth list
service Tag {
  rpc GetAuthorizedCards (google.protobuf.Empty) returns (GetAuthorizedCardsResponse) {}
  rpc AddAuthorizedCards (AddAuthorizedCardsRequest) returns (AddAuthorizedCardsResponse) {}
  rpc RemoveAuthorizedCard (RemoveCardRequest) returns (RemoveCardResponse) {}
  rpc GetAuthorizationHistory (google.protobuf.Empty) returns (AuthorizationHistoryResponse) {}
}

message AddAuthorizedCardsRequest {
  repeated AuthorizedCard AuthorizedCards = 1;
}

message AddAuthorizedCardsResponse {
  repeated string status = 1;
}

message GetAuthorizedCardsResponse {
  int32 Version = 1;
  repeated AuthorizedCard AuthorizedCards = 2;
}

message RemoveCardRequest {
  string TagId = 1;
}

message RemoveCardResponse {
  api.RequestStatus Status = 1;
}

message AuthorizationHistoryResponse {
  repeated AuthorizationHistoryEntry History = 1;
}

message AuthorizationHistoryEntry {
  google.protobuf.Timestamp Timestamp = 1;
  string TagId = 2;
  string Status = 3;
}

message AuthorizedCard{
  string TagId = 1;
  string Status = 2;
  optional google.protobuf.Timestamp ExpiryDate = 3;
}